# Generated by Django 4.1.4 on 2023-03-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_email_alter_product_mobile'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerregister')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
    ]
