# Generated by Django 4.1.4 on 2023-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_product_addtowishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerregister',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
