# Generated by Django 4.1.4 on 2023-03-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_rename_username_feedback_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Usernames',
            new_name='Username',
        ),
    ]
