# Generated by Django 4.1.4 on 2023-02-22 05:11

from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='', max_length=50)),
                ('Product_Description', models.TextField(max_length=300)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Product_Price', models.FloatField()),
                ('Mobile', models.CharField(max_length=10, verbose_name=seller.models.SellerRegister)),
                ('Email', models.EmailField(max_length=254, verbose_name=seller.models.SellerRegister)),
                ('Product_Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister')),
            ],
        ),
    ]
