# Generated by Django 4.1.4 on 2023-03-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister')),
            ],
        ),
    ]
