# Generated by Django 4.1.4 on 2023-03-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_feedbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='User',
            new_name='Username',
        ),
    ]
